### ISSUE TITLE
Progress bar in abg_python not on pypi

### ISSUE THREAD

**Issue by agurvich** [ageller/Firefly#127]
I am encountering issues with the installation as well:

```
Traceback (most recent call last):
  File "/home/david/projects/firefly_test/script/test.py", line 16, in <module>
    from firefly.data_reader import ArrayReader
  File "/home/david/.pyenv/versions/3.9.9/lib/python3.9/site-packages/firefly-3.1.0-py3.9.egg/firefly/data_reader/__init__.py", line 1, in <module>
    from .reader import Reader,SimpleReader,ArrayReader
  File "/home/david/.pyenv/versions/3.9.9/lib/python3.9/site-packages/firefly-3.1.0-py3.9.egg/firefly/data_reader/reader.py", line 11, in <module>
    from .particlegroup import ParticleGroup
  File "/home/david/.pyenv/versions/3.9.9/lib/python3.9/site-packages/firefly-3.1.0-py3.9.egg/firefly/data_reader/particlegroup.py", line 10, in <module>
    from .octree import Octree, init_octree_root_node
  File "/home/david/.pyenv/versions/3.9.9/lib/python3.9/site-packages/firefly-3.1.0-py3.9.egg/firefly/data_reader/octree.py", line 12, in <module>
    from abg_python.system_utils import printProgressBar
ImportError: cannot import name 'printProgressBar' from 'abg_python.system_utils' (/home/david/.pyenv/versions/3.9.9/lib/python3.9/site-packages/abg_python-1.0.5-py3.9.egg/abg_python/system_utils.py)
```

Running 
```
import abg_python
print(dir(abg_python.system_utils))

```

gives 

```
['StringIO', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'get_size', 'getfinsnapnum', 'os', 'suppressSTDOUTToFile', 'sys']
```

I think this is because the version of abg_python that is available on pip does not have the progressbar implementation.

_Originally posted by @ddhendriks in https://github.com/ageller/Firefly/issues/126#issuecomment-1199156024_

**Comment by agurvich** [comment]
updated abg_python to 1.0.6 and firefly to 3.1.1 to track the progress bar implementation.
