### ISSUE TITLE
pip installed Firefly is broken on Windows

### ISSUE THREAD

**Issue by ageller** [ageller/Firefly#161]
Firefly installation works on Mac.  But on Windows there is an error (copied below).  I suspect there may be a version issue for Windows packages.  I have a working Firefly install on my machine, so I will check the versions of all libraries and compare and test.  

```
$ firefly

Traceback (most recent call last):
  File "C:\Users\ageller\Anaconda3\envs\firefly_test\Scripts\firefly", line 12, in <module>
    from firefly.server import startHTTPServer, startFlaskServer
  File "C:\Users\ageller\Anaconda3\envs\firefly_test\lib\site-packages\firefly\server.py", line 15, in <module>
    from flask_socketio import SocketIO, emit, join_room, leave_room
  File "C:\Users\ageller\Anaconda3\envs\firefly_test\lib\site-packages\flask_socketio\__init__.py", line 9, in <module>
    from socketio import socketio_manage  # noqa: F401
  File "C:\Users\ageller\Anaconda3\envs\firefly_test\lib\site-packages\socketio\__init__.py", line 9, in <module>
    from .zmq_manager import ZmqManager
  File "C:\Users\ageller\Anaconda3\envs\firefly_test\lib\site-packages\socketio\zmq_manager.py", line 5, in <module>
    import eventlet.green.zmq as zmq
  File "C:\Users\ageller\Anaconda3\envs\firefly_test\lib\site-packages\eventlet\__init__.py", line 17, in <module>
    from eventlet import convenience
  File "C:\Users\ageller\Anaconda3\envs\firefly_test\lib\site-packages\eventlet\convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "C:\Users\ageller\Anaconda3\envs\firefly_test\lib\site-packages\eventlet\green\socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "C:\Users\ageller\Anaconda3\envs\firefly_test\lib\site-packages\eventlet\support\greendns.py", line 66, in <module>
    setattr(dns, pkg, import_patched('dns.' + pkg))
  File "C:\Users\ageller\Anaconda3\envs\firefly_test\lib\site-packages\eventlet\support\greendns.py", line 61, in import_patched
    return patcher.import_patched(module_name, **modules)
  File "C:\Users\ageller\Anaconda3\envs\firefly_test\lib\site-packages\eventlet\patcher.py", line 132, in import_patched
    return inject(
  File "C:\Users\ageller\Anaconda3\envs\firefly_test\lib\site-packages\eventlet\patcher.py", line 109, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
  File "C:\Users\ageller\Anaconda3\envs\firefly_test\lib\site-packages\dns\zone.py", line 86, in <module>
    class Zone(dns.transaction.TransactionManager):
  File "C:\Users\ageller\Anaconda3\envs\firefly_test\lib\site-packages\dns\zone.py", line 757, in Zone
    ) -> dns.rdtypes.ANY.SOA.SOA:
AttributeError: module 'dns.rdtypes' has no attribute 'ANY'
```

**Comment by ageller** [comment]
Noting that I recently installed Firefly in wsl (via `pip install firefly`) and didn't get any errors.  I have not tried on regular Windows recently.

**Comment by ageller** [comment]
Seems to work now... on Windows 11

```
conda create -n firefly-env python=3.14
conda activate firefly-env
pip install firefly
firefly
```

closing this issue
